### PR TITLE
feat: add an option to put modules on left

### PR DESCRIPTION
**Pull request by Darkham42**
### New vars
- modulesAtLeft

### Screenshot _(if applicable)_
Screen Shot 2022-06-10 at 02 55 09

### Code Quality Checklist _(Please complete)_
- [ x] All changes are backwards compatible
- [ x] There are no (new) build warnings or errors
- [ x] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [ ] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [ ] Bumps version, if new feature added

### CODE REVIEW

**Comment by ajnart** [comment]
Pretty cool :)

**Comment by Aimsucks** [comment]
> Pretty cool :) 

Did you review this?

**Comment by ajnart** [comment]
Actually I just did @Aimsucks 

@Darkham42 There is a mantine component called navbar for what you have
done in a hacky way, maybe we could figure out a way to get all the modules that have the option that you added (isAside boolean) (needs to be renamed obviously) 
and then display them in one after the other.

This way we have the same code in Navbar.tsx and Aside.tsx , and the user change chose their own preferences.

Also please fork from my repo from now on. I will merge @Aimsucks pr there 
(You can cherry pick your commits maybe ?)

**Comment by Darkham42** [comment]
Yes I'll do it right as u merge the PR.

**Comment by ajnart** [comment]
> Yes I'll do it right as u merge the PR.

Thanks for understanding

**Pull request closed without merging**
